This jupyter is aiming at provide some programming skill for 0-4 year old children limited on my knowledge.

# Kindergarten machine learning project guidance in python

### Author : PHBS SIQEF 2020 Research Assistance Group

When you start to code your own machine learning project, the first thing is to import relevant packages. In kindergarten you will usually be scared when you see the adult-level code,'cause they actually import so many packages!  
Feel free for that. You will never need to scrutinize all the packages syntex when you begin to code. They just did this in order to be beautiful. You can just import packages whenever you need them. 

Press M to write some comments, and use multiple # to indicate the title. Use space_space_enter to change to another line. If you meet some problems, try to breath and describe it clearly, then search it in google. You will always get the correct answer within the 20 page results.  

If you want to control the size and font of the markdown accurately,<font/><br>you may try </font><font color=#FF0000 size=2 face="Times New Roman">this way.

In [11]:
# But some basic packages you need to import, which will help you to load data.
import pandas as pd
import numpy as np
# from tabulate import tabulate
# If you want to time your program, you can
# import time

## 1. Find data

Finding relative data is the first step for your project or research. On quantity side, it's always great to find huge quantity data. For the normal machine learning case, it's appropriate to have 1000+ data.  

If you want to do something fancy, you can collect your own data. As machine learning needs so much data, usually you need to study beautifulsoup and some web crawler skills

But in dimension side, even with the help of auto-algorithms to delete the unnecessary data, I still urge you not to have too much dimension(like 1000+) due to your computer capacity. Actually you can do that if you graduate from kindergarten and get the hand of cloud computing or parallel computing.

In [3]:
# load local data if you already have it
?pd.read_csv
?pd.read_excel
?pd.read_stata
?pd.read_sql
# and others …
# print pd. then use tab to check the optional and its

It's okay if you download data and preprocess it in excel or other software. But in case that you need data from URL, it's convenient if you can input data without download to your local computer and proprecess it in Python.

Since not all of the website provide data API,let's use an local data case.

In [15]:
df = pd.read_excel('Banking_loss_events.xlsx')
df
# You can also check the data via 'df.head()' ,'df.tail()','tabulate(df)' or other methods.

,Region,Business,Name,Status,Risk Category,Risk Sub-Category,Discovery Date,Occurrence Start Date,Year,Net Loss,Recovery Amount,Estimated Gross Loss,Recovery Amount (percent)
0,EMEA,Retail Brokerage,LE−06−2,Under Review,"Clients, Products and Business Practices",Product Flaws,2007-01-01,2007-01-02,2007,296555.27,83035.4756,291100,28.0
1,North America,Retail Banking,LE−06−3,Approved,"Execution, Delivery and Process Management",Trade Counterparties,2007-01-03,2007-01-05,2007,87472.47,27116.4657,98400,31.0
2,Asia Pac,Retail Brokerage,LE−06−4,Not Started,"Clients, Products and Business Practices",Advisory Activities,2007-01-04,2007-01-06,2007,229395.38,59642.7988,230700,26.0
3,EMEA,Retail Banking,LE−06−5,In Progress,"Clients, Products and Business Practices",Product Flaws,2007-01-08,2007-01-11,2007,137925.29,34481.3225,137400,25.0
4,North America,Trading and Sales,LE−06−6,Under Review,"Execution, Delivery and Process Management",Reporting and Disclosure,2007-01-12,2007-01-14,2007,292160.41,90569.7271,288300,31.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1397,EMEA,Trading and Sales,z-LE-385,Under Review,"Execution, Delivery and Process Management",Vendors and Suppliers,2013-11-15,2013-11-17,2013,952743.86,285823.1580,952800,30.0
1398,EMEA,Trading and Sales,z-LE-538,In Progress,"Execution, Delivery and Process Management",Vendors and Suppliers,2014-01-24,2014-01-25,2014,122813.21,42984.6235,132200,35.0
1399,North America,Trading and Sales,z-LE-567,Not Started,"Execution, Delivery and Process Management",Vendors and Suppliers,2014-03-23,2014-03-26,2014,949052.11,208791.4642,946400,22.0
1400,Asia Pac,Retail Banking,z-LE-600,Rejected,"Execution, Delivery and Process Management",Vendors and Suppliers,2014-06-19,2014-06-20,2014,230710.76,18456.8608,232300,8.0
1401,North America,Retail Banking,z-LE-638,Rejected,"Execution, Delivery and Process Management",Vendors and Suppliers,2014-10-04,2014-10-05,2014,240558.72,19244.6976,238900,8.0

Now we have a quick view of the data. Before we continue, it's useful to see the category of different features.

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1402 entries, 0 to 1401
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Region                     1402 non-null   object
 1   Business                   1402 non-null   object
 2   Name                       1402 non-null   object
 3   Status                     1402 non-null   object
 4   Risk Category              1402 non-null   object
 5   Risk Sub-Category          1402 non-null   object
 6   Discovery Date             1402 non-null   datetime64[ns]
 7   Occurrence Start Date      1402 non-null   datetime64[ns]
 8   Year                       1402 non-null   int64
 9   Net Loss                   1402 non-null   float64
 10  Recovery Amount            1402 non-null   float64
 11  Estimated Gross Loss       1402 non-null   int64
 12  Recovery Amount (percent)  1402 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(2), object(6)
memory usage: 142.5+ KB

Ooops, we have plenty of 'object' features, which means they contain text and cannot put into our model directly. We need to do some transformation accordingly.  

Let's check the description statistics for numerical variables.

In [9]:
df.describe()

,Year,Net Loss,Recovery Amount,Estimated Gross Loss,Recovery Amount (percent)
count,1402.000000,1.402000e+03,1.402000e+03,1.402000e+03,1402.000000
mean,2011.019971,3.618860e+05,1.026123e+05,3.716211e+05,29.596291
std,2.239009,1.102039e+06,2.885603e+05,1.108328e+06,6.483356
min,2007.000000,-4.993440e+03,-1.947442e+03,-7.700000e+03,5.000000
25%,2009.000000,8.569924e+04,2.371198e+04,9.130000e+04,25.000000
50%,2011.000000,1.735251e+05,4.909423e+04,1.774000e+05,30.000000
75%,2013.000000,2.677119e+05,8.375998e+04,2.753000e+05,35.000000
max,2014.000000,1.168786e+07,3.774000e+06,1.169800e+07,40.000000

In [16]:
df['Region'].unique()

array(['EMEA', 'North America', 'Asia Pac'], dtype=object)

In [ ]:
# 选择 xm 这一列，是 Series 类型
df['xm']
# 选择 xm 这一列，是 DataFrame 类型
df[['xm']]
# 选择 xm, csrq 两列，是 DataFrame 类型，注意必须两个中括号
df[['xm','csrq']]
# 列顺序会根据输入顺序返回，所以这种方法可以改变列顺序
df = df[['csrq', 'xm']]
快速选取多行（注意不支持选取单行）：

df[:100]
支持一起使用：

df[['xm','csrq']][:100]